# Stage 2: Production Stage
FROM node:21-slim

# Set working directory
WORKDIR /app

# Copy only the necessary files from the build stage
COPY package*.json ./
COPY .next ./.next
COPY public ./public

# Install only production dependencies
RUN npm install --only=production
RUN npm prisma generate
# Expose the port that Next.js runs on
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "start"]
