import type {Metadata} from 'next'
import './globals.css'
import NavBar from "@/app/components/NavBar";
import {getServerSession} from "next-auth/next"
import {nextAuthOptions} from "@/app/api/auth/[...nextauth]/route";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" data-theme="light">
        <body className={"h-screen"}>
        <NavBar/>
        <main className={"md:container md:mx-auto"}>
            {children}
        </main>
        </body>
        </html>
    )
}
