import type {Metadata} from 'next'
import './globals.css'
import NavBar from "@/app/components/NavBar";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" data-theme="light">
        <body>
        <NavBar/>
        <main className={"md:container md:mx-auto"}>
           {children}
        </main>
        </body>
        </html>
    )
}
