apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace:  nuit-info-2023
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h