name: Semantic release

on:
  push:
    branches:
      - master
jobs:
  publish:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: |
          npx prisma generate
          npm run build
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          context: .
          file: ./Dockerfile.fast
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nuit-info-2023:latest,ghcr.io/${{ github.repository_owner }}/nuit-info-2023:${{ github.sha }},"ghcr.io/${{ github.repository_owner }}/nuit-info-2023:${{ steps.semantic.outputs.new_release_version }}"

      # update the kustomize image tag to the new version and push the changes to the repo

      #images:
      #  - newTag: 1.9.0 (can be found in manifests/kustomization.yaml)
      - name: Update manifest
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i 's/\(newTag: \).*/\1'${{ steps.semantic.outputs.new_release_version }}'/' manifests/kustomization.yaml
          git config --global user.email "semantic@release.com"
          git config --global user.name "GitHub Action"
          git add manifests/kustomization.yaml
          git commit -m "Update kustomize image tag to ${{ steps.semantic.outputs.new_release_version }}"
          git push          
  
