name: Semantic release

on:
  push:
    branches:
      - master
jobs:
  publish:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nuit-info-2023:latest,ghcr.io/${{ github.repository_owner }}/nuit-info-2023:${{ github.sha }},"ghcr.io/${{ github.repository_owner }}/nuit-info-2023:${{ steps.semantic.outputs.new_release_version }}"